project_id = "kljndbehjwfdyewgxgaw"

[functions.ask]
verify_jwt = true

[functions.courses]
verify_jwt = false

[functions.lessons]
verify_jwt = false

[functions.challenges]
verify_jwt = true

[functions.ai-hint]
verify_jwt = true
